server.port=7570

spring.application.name=web-api

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

spring.datasource.url=jdbc:oracle:thin:@//10.40.16.3:1521/db01
spring.datasource.username=data_usr
spring.datasource.password=dataicep1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none